### ISSUE TITLE
Avoid Concat In Loop

### ISSUE THREAD

**Issue by eleshar** [lightspeeddevelopment/lsx-blocks#6]
Concatenations inside a loop generate a lot of temporary variables. They are accumulated and tend to raise the memory usage, leading to slower performances.

https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/src/blocks/block-post-carousel/index.php#L43

**Comment by eleshar** [comment]
https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/src/blocks/block-post-grid/index.php#L27

**Comment by krugazul** [comment]
@jacquesvdhorst  this is a easy one to fix,   instead of having a variable which we add to during the loop, we are going to use an array.  We capture the values in the array, and then simply `implode()` them to create the 'string' of HTML.

1.  Change the variable to an array `$list_items_markup = array();` - [Code](https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/src/blocks/block-post-grid/index.php#L24)
2. Change all instances of `$list_items_markup .= ` to `$list_items_markup[] = `
3. Join the array values together with no '[separator](https://www.w3schools.com/php/func_string_implode.asp)' [here](https://github.com/lightspeeddevelopment/lsx-blocks/blob/44257c42a2462a74b8275b6ae64a830ff6e7e1d6/src/blocks/block-post-grid/index.php#L181),  `implode( '', $list_items_markup )`

**Comment by jacquesvdhorst** [comment]
@krugazul @ashleyshaw - I've added in the changes discussed here: https://github.com/lightspeeddevelopment/lsx-blocks/commit/fdd6129b414cdfa83680b2a872297432eeeb919b

**Comment by krugazul** [comment]
@eleshar I have tested this fix, it is working 100%. The block still outputs as expected, we have removed the concatenation.
